package at.uibk.dps.ee.control.agents;

import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.ExecutorService;

import at.uibk.dps.ee.control.graph.GraphAccess;
import at.uibk.dps.ee.control.management.EnactmentState;
import at.uibk.dps.ee.control.management.ExecutorProvider;
import net.sf.opendse.model.Task;

/**
 * The {@link AgentActivationExtraction} is responsible for the activation of the
 * {@link AgentExtraction}s to transmit the data generated by the tasks in the finished queue.
 * 
 * @author Fedor Smirnov
 *
 */
public class AgentActivationExtraction extends AgentContinuous implements AgentTaskCreator {

  protected final EnactmentState enactmentState;
  protected final ExecutorService executor;
  protected final GraphAccess graphAccess;
  protected final AgentFactoryExtraction agentFactory;
  protected final Set<AgentTaskListener> listeners = new HashSet<>();

  public AgentActivationExtraction(EnactmentState enactmentState, ExecutorProvider executorProvider,
      GraphAccess graphAccess, AgentFactoryExtraction agentFactory) {
    this.enactmentState = enactmentState;
    this.executor = executorProvider.getExecutorService();
    this.graphAccess = graphAccess;
    this.agentFactory = agentFactory;
  }

  @Override
  protected void operationOnTask(Task finishedTask) {
    // finds all of its out edges and start an extraction agent for each of them
    graphAccess.getOutEdges(finishedTask).forEach(edgeTuple -> executor
        .submit(agentFactory.createAgentTransmission(edgeTuple, getAgentTaskListeners())));
  }

  @Override
  protected Task getTaskFromBlockingQueue() {
    try {
      return enactmentState.takeFinishedTask();
    } catch (InterruptedException e) {
      throw new IllegalStateException("Extraction activation agent interrupted.", e);
    }
  }

  @Override
  public Set<AgentTaskListener> getAgentTaskListeners() {
    return getAgentTaskListeners();
  }

  @Override
  public void addAgentTaskListener(AgentTaskListener listener) {
    listeners.add(listener);
  }
}
